    create table addresses (
        default_address boolean,
        domicile boolean not null,
        residence boolean not null,
        id bigint generated by default as identity,
        user_id bigint,
        cap varchar(255) not null,
        city varchar(255) not null,
        civic varchar(255) not null,
        country varchar(255) not null,
        province varchar(255) not null,
        staircase varchar(255),
        street varchar(255) not null,
        primary key (id)
    );

    create table cards (
        id bigint generated by default as identity,
        card_holder varchar(255) not null,
        card_number varchar(255) not null,
        cvv varchar(255) not null,
        expiry_date varchar(255) not null,
        primary key (id)
    );

    create table cart_items (
        quantity integer not null,
        cart_id bigint not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        primary key (id)
    );

    create table carts (
        create_date date,
        id bigint generated by default as identity,
        user_id bigint not null unique,
        primary key (id)
    );

    create table categories (
        id bigint generated by default as identity,
        category varchar(255) not null unique,
        primary key (id)
    );

    create table order_details (
        quantity integer not null,
        total_price float(53) not null,
        id bigint generated by default as identity,
        order_id bigint not null,
        product_id bigint not null,
        size_id bigint,
        primary key (id)
    );

    create table orders (
        date date,
        order_price float(53),
        id bigint generated by default as identity,
        shipping_address bigint,
        user_id bigint,
        status varchar(255) check ((status in ('ORDINATO','PAGATO','SPEDITO','CONSEGNATO','ANNULLATO'))),
        primary key (id)
    );

    create table payment_methods (
        card_id bigint unique,
        id bigint generated by default as identity,
        user_id bigint not null,
        description varchar(255) not null,
        primary key (id)
    );

    create table products (
        discount float(53),
        discount_percentage float(53),
        price float(53),
        category_id bigint,
        id bigint generated by default as identity,
        description TEXT,
        gender varchar(255) check ((gender in ('MALE','FEMALE','UNISEX'))),
        image varchar(255),
        material varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table reviews (
        date date,
        rating integer not null,
        id bigint generated by default as identity,
        product_id bigint,
        user_id bigint,
        review TEXT,
        primary key (id)
    );

    create table sizes (
        quantity integer not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        size varchar(255) check ((size in ('XS','S','M','L','XL','XXL'))),
        primary key (id)
    );

    create table users (
        birthday date not null,
        create_date date,
        id bigint generated by default as identity,
        codice_fiscale varchar(255),
        email varchar(255) not null,
        last_name varchar(255) not null,
        name varchar(255) not null,
        password varchar(255) not null,
        phone varchar(255) not null,
        role varchar(255) not null check ((role in ('USER','ADMIN'))),
        primary key (id)
    );

    create table wishlist (
        create_date date,
        id bigint generated by default as identity,
        product_id bigint not null,
        user_id bigint not null,
        primary key (id)
    );

    alter table if exists addresses 
       add constraint FK1fa36y2oqhao3wgg2rw1pi459 
       foreign key (user_id) 
       references users;

    alter table if exists cart_items 
       add constraint FKpcttvuq4mxppo8sxggjtn5i2c 
       foreign key (cart_id) 
       references carts;

    alter table if exists cart_items 
       add constraint FK1re40cjegsfvw58xrkdp6bac6 
       foreign key (product_id) 
       references products;

    alter table if exists carts 
       add constraint FKb5o626f86h46m4s7ms6ginnop 
       foreign key (user_id) 
       references users;

    alter table if exists order_details 
       add constraint FKjyu2qbqt8gnvno9oe9j2s2ldk 
       foreign key (order_id) 
       references orders;

    alter table if exists order_details 
       add constraint FK4q98utpd73imf4yhttm3w0eax 
       foreign key (product_id) 
       references products;

    alter table if exists order_details 
       add constraint FKq1pfc355kfs5d2yjbdfhk4m5o 
       foreign key (size_id) 
       references sizes;

    alter table if exists orders 
       add constraint FKjln2fg6oii48r6v3f8pcm96o7 
       foreign key (shipping_address) 
       references addresses;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists payment_methods 
       add constraint FK2oiswbo86cg7m13qakop2yuay 
       foreign key (card_id) 
       references cards;

    alter table if exists payment_methods 
       add constraint FKin7rtmim3ljrrhh5kxbq27s2v 
       foreign key (user_id) 
       references users;

    alter table if exists products 
       add constraint FKog2rp4qthbtt2lfyhfo32lsw9 
       foreign key (category_id) 
       references categories;

    alter table if exists reviews 
       add constraint FKpl51cejpw4gy5swfar8br9ngi 
       foreign key (product_id) 
       references products;

    alter table if exists reviews 
       add constraint FKcgy7qjc1r99dp117y9en6lxye 
       foreign key (user_id) 
       references users;

    alter table if exists sizes 
       add constraint FKhs86kbnk4imwcyupgxp1g5dd2 
       foreign key (product_id) 
       references products;

    alter table if exists wishlist 
       add constraint FK6p7qhvy1bfkri13u29x6pu8au 
       foreign key (product_id) 
       references products;

    alter table if exists wishlist 
       add constraint FKtrd6335blsefl2gxpb8lr0gr7 
       foreign key (user_id) 
       references users;

