select.multiFilterProduct=SELECT p \
FROM Product p \
LEFT JOIN p.category c \
LEFT JOIN p.sizes s \
LEFT JOIN p.reviews r \
WHERE (:id IS NULL OR p.id = :id) \
AND (:name IS NULL OR p.name LIKE CONCAT(:name, '%')) \
AND (:categoryId IS NULL OR c.id = :categoryId) \
AND (:gender IS NULL OR p.gender = :gender) \
AND (:material IS NULL OR p.material LIKE CONCAT(:material, '%')) \
AND (:price IS NULL OR p.price = :price)
User.searchUsers=SELECT DISTINCT u FROM User u \n  LEFT JOIN FETCH u.addresses \n  WHERE (\:id IS NULL OR u.id \= \:id) \n  AND (\:name IS NULL OR u.name LIKE CAST(CONCAT(\:name, '%') AS string)) \n  AND (\:lastName IS NULL OR u.lastName LIKE CAST(CONCAT(\:lastName, '%') AS string)) \n  AND (\:email IS NULL OR UPPER(u.email) LIKE UPPER(CAST(CONCAT(\:email, '%') AS string))) \n  AND (\:codiceFiscale IS NULL OR u.codiceFiscale LIKE CAST(CONCAT(\:codiceFiscale, '%') AS string)) \n  AND (\:role IS NULL OR u.role \= \:role) \n  AND (\:createDate IS NULL OR u.createDate \= \:createDate)
