select.multiFilterProduct=SELECT p \
FROM Product p \
LEFT JOIN p.category c \
LEFT JOIN p.sizes s \
LEFT JOIN p.reviews r \
WHERE (:id IS NULL OR p.id = :id) \
AND (:name IS NULL OR p.name LIKE CONCAT(:name, '%')) \
AND (:categoryId IS NULL OR c.id = :categoryId) \
AND (:gender IS NULL OR p.gender = :gender) \
AND (:material IS NULL OR p.material LIKE CONCAT(:material, '%')) \
AND (:price IS NULL OR p.price = :price)
